import { PlanetInfo } from './planetarium.types';

export const PLANETS: PlanetInfo[] = [
  {
    id: 'sun',
    name: 'Sun',
    namePL: 'Słońce',
    subtitle: 'Nasza gwiazda',
    description:
      'Słońce to gwiazda w centrum naszego Układu Słonecznego. Jest kulą gorącej plazmy, która dostarcza energię niezbędną do życia na Ziemi. Stanowi 99,86% całkowitej masy Układu Słonecznego.',
    radiusKm: 696340,
    massKg: '1.99 × 10³⁰',
    gravity: 274,
    dayLengthHours: 609.12, // Rotation at equator (~25 days)
    yearLengthDays: 0,
    avgTempC: 5500, // Surface temperature
    moons: 0,
    color: '#FDB813',
    hasAtmosphere: true,
    hasRings: false,
    funFacts: [
      'Słońce to kula plazmy o temperaturze jądra 15 milionów °C',
      'Światło ze Słońca dociera do Ziemi w około 8 minut',
      'Słońce obraca się szybciej na równiku niż na biegunach',
      'W każdej sekundzie Słońce zamienia 600 mln ton wodoru w hel',
    ],
    keyMissions: [
      {
        name: 'Parker Solar Probe',
        year: 2018,
        agency: 'NASA',
        description: 'Najbliższa sonda przy Słońcu',
      },
      {
        name: 'Solar Orbiter',
        year: 2020,
        agency: 'ESA/NASA',
        description: 'Badanie biegunów Słońca',
      },
      {
        name: 'SOHO',
        year: 1995,
        agency: 'ESA/NASA',
        description: 'Obserwatorium Słońca',
      },
    ],
    composition: ['Wodór (73%)', 'Hel (25%)', 'Cięższe pierwiastki (2%)'],
  },
  {
    id: 'mercury',
    name: 'Mercury',
    namePL: 'Merkury',
    subtitle: 'Najbliższa Słońcu planeta',
    description:
      'Merkury to najmniejsza planeta Układu Słonecznego i najbliższa Słońcu. Jej powierzchnia jest pokryta kraterami, podobnie jak Księżyc. Temperatura na powierzchni waha się od -180°C nocą do ponad 400°C w dzień.',
    radiusKm: 2439.7,
    massKg: '3.30 × 10²³',
    gravity: 3.7,
    dayLengthHours: 1407.6,
    yearLengthDays: 88,
    avgTempC: 167,
    moons: 0,
    color: '#8c7853',
    hasAtmosphere: false,
    hasRings: false,
    funFacts: [
      'Rok na Merkurym trwa tylko 88 ziemskich dni',
      'Merkury ma największą różnicę temperatur między dniem a nocą',
      'Mimo bliskości Słońca, Merkury nie jest najgorętszą planetą',
      'Na Merkurym występuje zjawisko "podwójnego wschodu Słońca"',
    ],
    keyMissions: [
      {
        name: 'Mariner 10',
        year: 1974,
        agency: 'NASA',
        description: 'Pierwsza sonda, która przeleciała obok Merkurego',
      },
      {
        name: 'MESSENGER',
        year: 2011,
        agency: 'NASA',
        description: 'Pierwsza sonda na orbicie Merkurego',
      },
      {
        name: 'BepiColombo',
        year: 2018,
        agency: 'ESA/JAXA',
        description: 'Misja w trakcie lotu, dotrze w 2025',
      },
    ],
    composition: ['Żelazo (70%)', 'Krzemiany (30%)', 'Cienka egzosfera'],
  },
  {
    id: 'venus',
    name: 'Venus',
    namePL: 'Wenus',
    subtitle: 'Bliźniaczka Ziemi',
    description:
      'Wenus jest drugą planetą od Słońca i najbardziej podobną do Ziemi pod względem wielkości. Jej gęsta atmosfera zatrzymuje ciepło, czyniąc ją najgorętszą planetą. Wenus obraca się w kierunku przeciwnym do większości planet.',
    radiusKm: 6051.8,
    massKg: '4.87 × 10²⁴',
    gravity: 8.87,
    dayLengthHours: 5832.5,
    yearLengthDays: 225,
    avgTempC: 464,
    moons: 0,
    color: '#e6c87a',
    hasAtmosphere: true,
    hasRings: false,
    funFacts: [
      'Dzień na Wenus trwa dłużej niż rok (243 vs 225 dni ziemskich)',
      'Wenus obraca się w kierunku przeciwnym do większości planet',
      'Ciśnienie atmosferyczne jest 90 razy większe niż na Ziemi',
      'To najjaśniejszy obiekt na niebie po Słońcu i Księżycu',
    ],
    keyMissions: [
      {
        name: 'Venera 7',
        year: 1970,
        agency: 'ZSRR',
        description: 'Pierwsze udane lądowanie na innej planecie',
      },
      {
        name: 'Magellan',
        year: 1990,
        agency: 'NASA',
        description: 'Zmapował 98% powierzchni radarowo',
      },
      {
        name: 'Akatsuki',
        year: 2015,
        agency: 'JAXA',
        description: 'Obecnie bada atmosferę Wenus',
      },
    ],
    composition: ['CO₂ (96.5%)', 'N₂ (3.5%)', 'Chmury kwasu siarkowego'],
  },
  {
    id: 'earth',
    name: 'Earth',
    namePL: 'Ziemia',
    subtitle: 'Nasz kosmiczny dom',
    description:
      'Ziemia to trzecia planeta od Słońca i jedyna znana nam planeta, na której istnieje życie. Posiada ciekłą wodę na powierzchni, ochronną atmosferę i pole magnetyczne chroniące przed promieniowaniem kosmicznym.',
    radiusKm: 6371,
    massKg: '5.97 × 10²⁴',
    gravity: 9.81,
    dayLengthHours: 24,
    yearLengthDays: 365.25,
    avgTempC: 15,
    moons: 1,
    color: '#6b93d6',
    hasAtmosphere: true,
    hasRings: false,
    funFacts: [
      'Ziemia jest jedyną planetą nie nazwaną od boga/bogini',
      '71% powierzchni pokrywają oceany',
      'Pole magnetyczne Ziemi chroni nas przed wiatrem słonecznym',
      'Ziemia jest najbardziej gęstą planetą Układu Słonecznego',
    ],
    keyMissions: [
      {
        name: 'Sputnik 1',
        year: 1957,
        agency: 'ZSRR',
        description: 'Pierwszy sztuczny satelita',
      },
      {
        name: 'ISS',
        year: 1998,
        agency: 'NASA/Roscosmos/ESA/JAXA',
        description: 'Międzynarodowa Stacja Kosmiczna',
      },
      {
        name: 'Sentinel',
        year: 2014,
        agency: 'ESA',
        description: 'Program obserwacji Ziemi',
      },
    ],
    composition: ['N₂ (78%)', 'O₂ (21%)', 'Ar, CO₂, H₂O (1%)'],
  },
  {
    id: 'moon',
    name: 'Moon',
    namePL: 'Księżyc',
    subtitle: 'Naturalny satelita Ziemi',
    description:
      'Księżyc to jedyny naturalny satelita Ziemi i piąty co do wielkości księżyc w Układzie Słonecznym. Jest jedynym ciałem niebieskim poza Ziemią, na którym stanął człowiek.',
    radiusKm: 1737.4,
    massKg: '7.35 × 10²²',
    gravity: 1.62,
    dayLengthHours: 708.7, // ~29.5 Earth days (synchronous rotation)
    yearLengthDays: 27.3, // Orbital period around Earth
    avgTempC: -20, // Average (varies greatly)
    moons: 0,
    color: '#aaaaaa',
    hasAtmosphere: false,
    hasRings: false,
    funFacts: [
      'Księżyc oddala się od Ziemi o 3.8 cm rocznie',
      'Ta sama strona Księżyca jest zawsze zwrócona ku Ziemi',
      'Księżyc powstał z kolizji Ziemi z obiektem wielkości Marsa',
      '12 ludzi chodziło po powierzchni Księżyca (1969-1972)',
    ],
    keyMissions: [
      {
        name: 'Apollo 11',
        year: 1969,
        agency: 'NASA',
        description: 'Pierwsze lądowanie człowieka',
      },
      {
        name: 'Luna 2',
        year: 1959,
        agency: 'ZSRR',
        description: 'Pierwsza sonda na Księżycu',
      },
      {
        name: 'Artemis',
        year: 2024,
        agency: 'NASA',
        description: 'Powrót człowieka na Księżyc',
      },
    ],
    composition: ['Krzemiany', 'Tlenek żelaza', 'Tlenek glinu', 'Lód wodny (bieguny)'],
  },
  {
    id: 'mars',
    name: 'Mars',
    namePL: 'Mars',
    subtitle: 'Czerwona Planeta',
    description:
      'Mars to czwarta planeta od Słońca, znana jako Czerwona Planeta ze względu na tlenek żelaza pokrywający jej powierzchnię. Posiada najwyższy wulkan (Olympus Mons) i największy kanion (Valles Marineris) w Układzie Słonecznym.',
    radiusKm: 3389.5,
    massKg: '6.42 × 10²³',
    gravity: 3.71,
    dayLengthHours: 24.6,
    yearLengthDays: 687,
    avgTempC: -65,
    moons: 2,
    color: '#c1440e',
    hasAtmosphere: true,
    hasRings: false,
    funFacts: [
      'Olympus Mons jest 3x wyższy niż Mount Everest',
      'Mars ma dwa małe księżyce: Fobos i Deimos',
      'Dzień na Marsie (sol) trwa tylko 37 minut dłużej niż ziemski',
      'Na Marsie występują burze piaskowe obejmujące całą planetę',
    ],
    keyMissions: [
      {
        name: 'Viking 1',
        year: 1976,
        agency: 'NASA',
        description: 'Pierwsze udane lądowanie na Marsie',
      },
      {
        name: 'Curiosity',
        year: 2012,
        agency: 'NASA',
        description: 'Łazik badający krater Gale',
      },
      {
        name: 'Perseverance',
        year: 2021,
        agency: 'NASA',
        description: 'Szuka śladów życia, zbiera próbki',
      },
    ],
    composition: ['CO₂ (95%)', 'N₂ (2.7%)', 'Ar (1.6%)'],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    namePL: 'Jowisz',
    subtitle: 'Król planet',
    description:
      'Jowisz to największa planeta Układu Słonecznego - mogłaby pomieścić ponad 1300 Ziem. Jest gazowym gigantem z charakterystyczną Wielką Czerwoną Plamą - burzą trwającą od co najmniej 400 lat.',
    radiusKm: 69911,
    massKg: '1.90 × 10²⁷',
    gravity: 24.79,
    dayLengthHours: 9.9,
    yearLengthDays: 4333,
    avgTempC: -110,
    moons: 95,
    color: '#d8ca9d',
    hasAtmosphere: true,
    hasRings: true,
    funFacts: [
      'Jowisz ma najkrótszy dzień ze wszystkich planet (ok. 10 godzin)',
      'Wielka Czerwona Plama jest większa niż Ziemia',
      'Jowisz ma co najmniej 95 księżyców',
      'Pole magnetyczne Jowisza jest 20 000 razy silniejsze niż ziemskie',
    ],
    keyMissions: [
      {
        name: 'Pioneer 10',
        year: 1973,
        agency: 'NASA',
        description: 'Pierwszy przelot obok Jowisza',
      },
      {
        name: 'Galileo',
        year: 1995,
        agency: 'NASA',
        description: 'Pierwsza sonda na orbicie Jowisza',
      },
      {
        name: 'Juno',
        year: 2016,
        agency: 'NASA',
        description: 'Bada strukturę i pole magnetyczne',
      },
    ],
    composition: ['H₂ (90%)', 'He (10%)', 'Ślady metanu i amoniaku'],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    namePL: 'Saturn',
    subtitle: 'Planeta pierścieni',
    description:
      'Saturn to szósta planeta od Słońca, słynąca z imponujących pierścieni składających się głównie z lodu i skał. Jest to drugi co do wielkości gazowy gigant w naszym układzie.',
    radiusKm: 58232,
    massKg: '5.68 × 10²⁶',
    gravity: 10.44,
    dayLengthHours: 10.7,
    yearLengthDays: 10759,
    avgTempC: -140,
    moons: 146,
    color: '#ead6b8',
    hasAtmosphere: true,
    hasRings: true,
    funFacts: [
      'Pierścienie Saturna rozciągają się na 282 000 km, ale mają tylko 10 m grubości',
      'Saturn jest jedyną planetą mniej gęstą od wody',
      'Księżyc Tytan ma gęstą atmosferę i jeziora ciekłego metanu',
      'Saturn ma 146 potwierdzonych księżyców',
    ],
    keyMissions: [
      {
        name: 'Voyager 1',
        year: 1980,
        agency: 'NASA',
        description: 'Szczegółowe zdjęcia pierścieni',
      },
      {
        name: 'Cassini-Huygens',
        year: 2004,
        agency: 'NASA/ESA',
        description: '13 lat badań, lądownik na Tytanie',
      },
      {
        name: 'Dragonfly',
        year: 2027,
        agency: 'NASA',
        description: 'Przyszła misja na Tytan (dron)',
      },
    ],
    composition: ['H₂ (96%)', 'He (3%)', 'Metan, amoniak, woda'],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    namePL: 'Uran',
    subtitle: 'Lodowy gigant',
    description:
      'Uran to siódma planeta od Słońca, charakteryzująca się wyjątkowym nachyleniem osi - obraca się praktycznie "na boku". Jest lodowym gigantem z atmosferą zawierającą metan, nadającą mu niebieskozielony kolor.',
    radiusKm: 25362,
    massKg: '8.68 × 10²⁵',
    gravity: 8.69,
    dayLengthHours: 17.2,
    yearLengthDays: 30687,
    avgTempC: -195,
    moons: 28,
    color: '#d1e7e7',
    hasAtmosphere: true,
    hasRings: true,
    funFacts: [
      'Uran obraca się na boku (nachylenie osi 98°)',
      'Rok na Uranie trwa 84 ziemskie lata',
      'Ma 13 znanych pierścieni (ciemnych i trudnych do zobaczenia)',
      'Temperatura w chmurach może spaść do -224°C',
    ],
    keyMissions: [
      {
        name: 'Voyager 2',
        year: 1986,
        agency: 'NASA',
        description: 'Jedyna sonda, która odwiedziła Urana',
      },
      {
        name: 'Uranus Orbiter',
        year: 2031,
        agency: 'NASA',
        description: 'Proponowana misja (w planach)',
      },
    ],
    composition: ['H₂ (83%)', 'He (15%)', 'CH₄ (2%)'],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    namePL: 'Neptun',
    subtitle: 'Wietrzny świat',
    description:
      'Neptun to ósma i najdalsza planeta Układu Słonecznego. Posiada najsilniejsze wiatry w całym układzie, osiągające prędkość ponad 2000 km/h. Jego intensywnie niebieski kolor pochodzi od metanu w atmosferze.',
    radiusKm: 24622,
    massKg: '1.02 × 10²⁶',
    gravity: 11.15,
    dayLengthHours: 16.1,
    yearLengthDays: 60190,
    avgTempC: -200,
    moons: 16,
    color: '#5b5ddf',
    hasAtmosphere: true,
    hasRings: true,
    funFacts: [
      'Neptun ma najsilniejsze wiatry w Układzie Słonecznym (2100 km/h)',
      'Rok na Neptunie trwa 165 ziemskich lat',
      'Neptun został odkryty matematycznie, zanim go zaobserwowano',
      'Księżyc Tryton jest jedynym dużym księżycem na orbicie wstecznej',
    ],
    keyMissions: [
      {
        name: 'Voyager 2',
        year: 1989,
        agency: 'NASA',
        description: 'Jedyna sonda, która odwiedziła Neptuna',
      },
      {
        name: 'Neptune Odyssey',
        year: 2033,
        agency: 'NASA',
        description: 'Proponowana misja (koncepcja)',
      },
    ],
    composition: ['H₂ (80%)', 'He (19%)', 'CH₄ (1%)'],
  },
];

export const PLANET_ORDER = [
  'sun',
  'mercury',
  'venus',
  'earth',
  'moon',
  'mars',
  'jupiter',
  'saturn',
  'uranus',
  'neptune',
];

export function getPlanetById(id: string): PlanetInfo | undefined {
  return PLANETS.find((p) => p.id === id);
}

export function getPlanetIndex(id: string): number {
  return PLANET_ORDER.indexOf(id);
}
